spring:
    datasource:
        url: ${DB_JDBC_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Swagger
springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /api-docs/json
        groups:
            enable: true
    cache:
        disabled: true
    use-fqn: true
    default-consumes-media-type: application/json;charset=UTF-8
    default-produces-media-type: application/json;charset=UTF-8
